kind: pipeline
type: docker
name: default
pipeline:
  publish:
    image: plugins/docker
    insecure: "true"
    registry: registry.tonyjhang.tk:5000
    repo: registry.tonyjhang.tk:5000/${DRONE_REPO}-${DRONE_BRANCH}
    dockerfile: ./Dockerfile
    tags:
      - latest
      - ${DRONE_COMMIT}

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    secrets:
      - source: k8s_server
        target: plugin_kubernetes_server
      - source: k8s_cert
        target: plugin_kubernetes_cert
      - source: k8s_token
        target: plugin_kubernetes_token
    namespace: default
    deployment: websocket
    repo: registry.tonyjhang.tk:5000/${DRONE_REPO}-${DRONE_BRANCH}
    container: websocket
    tag: ${DRONE_COMMIT}
