kind: pipeline
type: docker
name: default
pipeline:
  publish:
    image: plugins/docker
    insecure: "true"
    registry: registry.tonyjhang.tk:5000
    repo: registry.tonyjhang.tk:5000/${DRONE_REPO}-${DRONE_BRANCH}
    dockerfile: ./Dockerfile
    tags:
      - latest
      - ${DRONE_COMMIT}

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    secrets:
      - source: k8s_server
        target: plugin_kubernetes_server
      - source: k8s_cert
        target: plugin_kubernetes_cert
      - source: k8s_token
        target: plugin_kubernetes_token
#    kubernetes_server: https://k3d-mycluster-serverlb:6443
#    kubernetes_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTXpBME9EWXlPVGN3SGhjTk1qRXdPVEF4TURnMU1UTTNXaGNOTXpFd09ETXdNRGcxTVRNMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTXpBME9EWXlPVGN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUTkhHOG45bGRaWCtnY3FpUTlDU2hiK2NQNjdSN2hoS2tTM1BnMmZCVTYKM2YyMlZ2c0RjQ2dlNnBydXZ5dHVpTlU4WnNESkVyTHV0YitCd2JjK3VQZEpvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0J#VXdBd0VCL3pBZEJnTlZIUTRFRmdRVTZQem9EVjlISWd5blNHT2pqOU90ClA5cWRERVV3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUpCSWU2WS9LQ2cxZzVBbndtQmdlY2laVERDVDNVazEKOE9IOW9IcU4yaTBuQWlBYXZXTitRdm1Bd0VXbHdFaWhvYlBwMnBqcVNEZnhQUk95UFNOZCtFTkp5Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#    kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjVmbTRCXzRYS1dzMGNwclpDZEx5amRKdGtSMHVZUVhiQUtwS2Q3OUlfd1kifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRyb25lLWRlcGxveS10b2tlbi13d3Q1dyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkcm9uZS1kZXBsb3kiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI2NGRjOTY5Mi1mMGY5LTQwZGMtOTVkYy0zNjRiN2Ux#GE1MmUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpkcm9uZS1kZXBsb3kifQ.qqmOzlAjO2qOGA9xDebl2kEsyAQmZfMQmIiir8hLIOD6hkWXQyqenbKtNeamjXtsQCQYYvQHzQnND_wGulYk8dBJ1lslNh_HZTRYOda2lbmJatD_FmJe0NPUgfOeCwnXpo6HSLVDbxQSnoPcazZWjiCbkVKqhEge0pEQAjAuh_i0KRteAJhFcJ6zqgiapnZASAdeVGDLyhXD8Tn1acUy9JqC_AgF1dbmwSBSThQnzhVichsJmfXX3NJq9fei3uXIy2Swl4KMOCN7W70sO-HuHUYYIgbEaqJjjYDScYWr98Q3GIYSUF9Gmp3h5qKJAMHEw0QMqQjVvmwH6zkj7TLMmw
    namespace: default
    deployment: websocket
    repo: registry.tonyjhang.tk:5000/${DRONE_REPO}-${DRONE_BRANCH}
    container: websocket
    tag: ${DRONE_COMMIT}
