apiVersion: v1
kind: Service
metadata:
  name: websocket
  namespace: develop
  labels:
    app: websocket
    repo: websocket
    product: test
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8899
  selector:
    app: websocket
    repo: websocket
    product: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  namespace: develop
  labels:
    app: websocket
    repo: websocket
    product: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
      repo: websocket
      product: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: websocket
        repo: websocket
        product: test
    spec:
      restartPolicy: Always
      containers:
      - name: websocket
        image: mayday6206/websocket-master:latest
        imagePullPolicy: Always
        command: ["./server"]
