apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: default
data:
  traefik.toml: |

    [entryPoints]
    #  [entryPoints.web]
    #    address = ":80"

      [entryPoints.websecure]
        address = ":443"
        [entryPoints.websecure.forwardedHeaders]
          insecure = true

    [accessLog]

    [log]
      level = "INFO"

    [api]
      dashboard = true
      insecure = true

    [ping]
      entryPoint = "traefik"

    [providers]
      [providers.file]
        filename = "/etc/traefik/dynamic_conf.toml"

  dynamic_conf.toml: |

    [tls.stores]
      [tls.stores.default]
        [tls.stores.default.defaultCertificate]
          certFile = "/certs/tls.crt"
          keyFile  = "/certs/tls.key"

    [http.routers]
      [http.routers.router1]
        rule = "Host(`websocket.tonyjhang.tk`) && PathPrefix(`/echo`)"
        entryPoints = ["websecure"]
        service = "websocket"
        priority = 2
          [http.routers.router1.tls]

    [http.services]
      [http.services.websocket.loadBalancer]
        [[http.services.websocket.loadBalancer.servers]]
          url = "http://websocket"
